name: Generar hash de carpeta source

on:
  push:
    branches:
      - main
      - master

jobs:
  generar-hash:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Ejecutar script de hash
        run: python source/macros/_hash_version.py

      - name: Guardar TXT en el repositorio
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add hash_source.txt
          git commit -m "Generar hash automático de source" || echo "No hay cambios para commitear"
          git push
